// Generates a minimal icon stylesheet containing ONLY the icons this app uses.
//
// WHY
// @phosphor-icons/web ships a stylesheet with 1,530 icon classes (~76 KB) and
// four copies of the font (woff2, woff, ttf and a 3 MB svg). We use ~50 icons,
// and every browser we care about takes the woff2. Guests load this on a phone,
// on party wifi, often as a first visit — so the waste is paid by exactly the
// people least able to afford it.
//
// This reads the icon names actually referenced in src/lib/icons.js, pulls just
// those rules out of the upstream stylesheet, and writes them plus a single
// @font-face pointing at the woff2 we copy into src/assets/fonts/.
//
// The glyphs are byte-for-byte the upstream ones — this only removes rules and
// font formats, so rendering cannot change.
//
// Run with:  npm run icons:build
import { readFile, writeFile, mkdir, copyFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const pkg = join(root, 'node_modules', '@phosphor-icons', 'web', 'src', 'regular')
const fontsOut = join(root, 'src', 'assets', 'fonts')
const cssOut = join(root, 'src', 'styles', 'icons.css')

// Which icons do we actually use? The `I` map in icons.js is the single source
// of truth, so read the names straight out of it rather than keeping a second
// list that could drift.
const iconsJs = await readFile(join(root, 'src', 'lib', 'icons.js'), 'utf8')
const mapBlock = iconsJs.match(/export const I = \{([\s\S]*?)\n\}/)
if (!mapBlock) throw new Error('Could not find the `export const I = {...}` map in src/lib/icons.js')

const used = [...new Set(
  [...mapBlock[1].matchAll(/:\s*'([a-z0-9-]+)'/g)].map((m) => m[1])
)].sort()

// Pull the matching rules out of the upstream stylesheet.
const upstreamCss = await readFile(join(pkg, 'style.css'), 'utf8')

const rules = []
const missing = []
for (const name of used) {
  // e.g.  .ph.ph-mask-happy:before { content: "\e3f4"; }
  const re = new RegExp(String.raw`\.ph\.ph-${name}:before\s*\{[^}]*\}`, 'i')
  const found = upstreamCss.match(re)
  if (found) rules.push(found[0].replace(/\s+/g, ' ').trim())
  else missing.push(name)
}

if (missing.length > 0) {
  // Fail loudly: a silently missing icon renders as an empty box in production.
  throw new Error(`No rule found in upstream CSS for: ${missing.join(', ')}`)
}

await mkdir(fontsOut, { recursive: true })
await copyFile(join(pkg, 'Phosphor.woff2'), join(fontsOut, 'Phosphor.woff2'))

const css = `/* GENERATED by scripts/build-icons.mjs — do not edit by hand.
 * Run: npm run icons:build   (after changing the I map in src/lib/icons.js)
 *
 * Only the ${rules.length} icons this app uses, and only the woff2 format.
 * Replaces @phosphor-icons/web's full stylesheet (1530 rules) and its
 * woff/ttf/svg copies of the font. The glyph data is unchanged upstream
 * Phosphor Regular, so icons render exactly as before.
 */
@font-face {
  font-family: "Phosphor";
  src: url("../assets/fonts/Phosphor.woff2") format("woff2");
  font-weight: normal;
  font-style: normal;
  font-display: block; /* avoid a flash of unstyled boxes */
}

.ph {
  font-family: "Phosphor" !important;
  speak: never;
  font-style: normal;
  font-weight: normal;
  font-variant: normal;
  text-transform: none;
  line-height: 1;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

${rules.join('\n')}
`

await writeFile(cssOut, css, 'utf8')

console.log(`src/styles/icons.css written: ${rules.length} icons (was 1530)`)
console.log(`src/assets/fonts/Phosphor.woff2 copied (woff/ttf/svg no longer shipped)`)
